# -*- coding: utf-8 -*-
"""my_script.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ppFrKCDrRKcDvJzP8ZkzHo9WVIwXLW7F
"""

pip install streamlit

import streamlit as st
import pandas as pd

link = "https://raw.githubusercontent.com/murpi/wilddata/master/quests/cars.csv"
voiture = pd.read_csv(link)
st.write(voiture)

import seaborn as sns
viz_correlation = sns.heatmap(voiture.corr(),
								center=0,
								cmap = sns.color_palette("vlag", as_cmap=True)
								)

st.pyplot(viz_correlation.figure)

import numpy as np
chart_data = pd.DataFrame(np.random.randn(20, 3), columns=["mpg", "cylinders", "cubicinches"])
st.bar_chart(chart_data)

cont = st.sidebar.radio("Continent of analysis", voiture["continent"].unique())
filtered_data = voiture[voiture["continent"] == cont]
st.title('Analyse mpg')
st.bar_chart(filtered_data, x="year", y="mpg")